site_name: Python Versity
site_description: Quant Coding Versity for Python
site_author: Dr Saad Laouadi
site_url: https://qcversity.github.io/python-versity

nav:
  - About: about.md
  - Introduction: index.md
  - Development Tools:
      - Unix-Like Systems Tools:
        - DevTools/UnixLike-Systems-Tools.md
      - Windows Tools:
        - DevTools/Windows Tools.md
  - Environment Setup:
      - Unix-Based Systems Setup: Envsetup/Unix-Based Systems Setup.md
      - Windows Setup: Envsetup/Windows Setup.md
  - Built-in Methods:
      - Introduction:
        - Built-in Methods/introduction.md
      - Abs Method: 'Built-in Methods/Abs method.md'



theme:
  name: null
  custom_dir: theme/
  # extra_css:
  #   - css/main.css
  # logo: img/logo.bmp
  # features:
  #   - navigation.footer
  #   - navigation.instant
  #   - navigation.top
  #   - content.code.annotate
  #   - search.suggest
  #   - search.highlight

plugins:
  - search
  - exclude-search:
      exclude: [newsletter/*]
  - autolinks
  # - git-revision-date-localized:
  #     type: timeago
  - minify:
      minify_html: true
  - section-index
  # - mkdocs-newsletter

extra:
  article_nav_top: false
  article_nav_bottom: false
  history_buttons: false
  version: 1.0.0
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/qcversity
    - icon: fontawesome/solid/rss
      link: https://qcversity.github.io/blue-book/newsletter/0_newsletter_index


repo_name: qcversity/python-versity
repo_url: https://github.com/qcversity/python-versity
